# Floating Point Format Specifiers Support
CONFIG_CBPRINTF_FP_SUPPORT=y
# I2C Support
CONFIG_I2C=y
# Logger module
CONFIG_LOG=y
# Nordic DK library
CONFIG_DK_LIBRARY=y
# Bluetooth LE
CONFIG_BT=y
# Bluetooth Peripheral Role
CONFIG_BT_PERIPHERAL=y
# Increase stack size for the main thread and System Workqueue
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048
